# -*- coding: utf-8 -*-
"""Cópia de Web Scrapping Monitoração de Preço Versão GitHub

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_TAwn0uuqX3fDQxQNRCmz1QfM-9zinRh
"""

import os
import requests
from bs4 import BeautifulSoup
from datetime import datetime
import pandas as pd


# PASSO 1 > COLETA DE DADOS

# link do livro que queremos monitorar
url = "https://books.toscrape.com/catalogue/we-love-you-charlie-freeman_954/index.html"

# Ação de visitar o site

resposta = requests.get(url)

# Vamos converter o conteúdo do site em HTML para que o Python entenda
site = BeautifulSoup(resposta.text, "html.parser")

# Após isso, o python guardou o site em htmlk dentro da varial "site"

# Proximo passo é inspecionar o site para analisar onde ele está guardando as informações que precisamos.

# Buscando o título (está na tag <H1>)
titulo = site.find("h1").text
print(f"Produto encontrado: {titulo}")

# Buscando o preço (está na tag <P> com a CLASSE "price_color")

# Ele vai retornar o preço em String (texto)

preco_texto = site.find("p", class_="price_color").text
print(f"Preço bruto do site: {preco_texto}")

# Remove o símbolo da moeda (£) e substitui por nada, deixando só os números
preco_limpo = preco_texto.replace("Â", "").replace("£", "").strip()

# Transforma o texto em um número decimal (Float)
preco_final = float(preco_limpo)

# Mostra o preço final e o tipo da variavel atual

print(f"Preço final: {preco_final}")
print(type(preco_final)) # Serve para mostrar o tipo da variavel preco final e deve exibir <class 'float'>








# PASSO 2 > ADICIONAR ESSES DADOS A UMA TABELA









# 1. Captura a data e hora exata do momento da raspagem
data_atual = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# 2. Cria um dicionário (uma linha da nossa tabela) com todas as informações
novos_dados = {
    "Data": [data_atual],
    "Produto": [titulo],
    "Preco": [preco_final]
}

    # DIFERENCIA DO LOCAL: ARMAZENAMENTO EM TABELA PARA O GIT AUTOMATIZAR

    # DF NOVO = Dataframe novo

df_novo = pd.DataFrame(novos_dados)

# Nome do arquivo que vai ficar no GitHub
nome_arquivo = "historico_precos.csv"

# Se o arquivo já existir no repositório, adiciona a linha. Se não, cria.
if os.path.exists(nome_arquivo):
    df_novo.to_csv(nome_arquivo, mode="a", header=False, index=False)
    print("Dados adicionados ao histórico com sucesso!")
else:
    df_novo.to_csv(nome_arquivo, index=False)
    print("Arquivo 'historico_precos.csv' criado com a primeira linha!")





    # ==========================================
# PASSO 3: ANÁLISE E ALERTA INTELIGENTE
# ==========================================

# 1. Lemos todo o histórico de preços que guardamos até agora, criando uma nova variavel chamada historico
historico = pd.read_csv(nome_arquivo)

# 2. Calculamos a média de todos os preços registados no ficheiro
preco_medio = historico["Preco"].mean()

print(f"--------------------------")
print(f"--- ANÁLISE DE MERCADO ---")
print(f"Preço Atual: {preco_final}")
print(f"Preço Médio Histórico: {preco_medio:.2f}")
print(f"--------------------------")



# 3. A Tomada de Decisão (O Alerta)

# Se o preço de hoje for mais barato que a média histórica, disparamos o alerta

if preco_final < preco_medio:
    print("🚨 ALERTA DE PROMOÇÃO: O preço baixou! Hora de comprar! 🚨")
else:
    print("O preço está igual ou acima da média. Melhor esperar mais um pouco. ⏳")

